name: Sync `documentation` directory to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Find and replace image file paths
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "../"
          replace: "https://raw.githubusercontent.com/Stardust-Platform/Documentation/main/"
          regex: false
          include: guides/*

      - name: Sync Stardust Guides
        uses: readmeio/rdme@7.2.0
        with:
          rdme: docs ./guides --key=${{ secrets.README_API_KEY }} --version=0.0.0

          ##      - name: Sync Stardust Core OpenAPI file
          ##        uses: readmeio/rdme@7.2.0
          ##        with:
          ##          rdme: openapi ./ref/stardustCore.json --key=7jxMDILq5wZxTRaa4uhafttXDC8tcCOd --version=0.0.0
