name: Sync dev branch to ReadMe

# Run workflow for every push to the `dev` branch
on:
  push:
    branches:
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Find and replace image file paths
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "../"
          replace: "https://raw.githubusercontent.com/Stardust-Platform/Documentation/dev/"
          regex: false
          include: guides/*

      - name: Find and replace quick start category ID
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "QUICK_START_ID"
          replace: "62c478c8cba0f5004906245d"
          regex: false
          include: guides/*

      - name: Find and replace admin dashboard category ID
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "ADMIN_DASHBOARD_ID"
          replace: "626c5405d8dcda006293ca0d"
          regex: false
          include: guides/*

      - name: Find and replace stardust APIs category ID
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "STARDUST_APIS_ID"
          replace: "62c478e4217e3f009873123a"
          regex: false
          include: guides/*

      - name: Sync Stardust Guides
        uses: readmeio/rdme@7.2.0
        with:
          rdme: docs ./guides --key=${{ secrets.README_API_KEY }} --version=0.0.0

          ##      - name: Sync Stardust Core OpenAPI file
          ##        uses: readmeio/rdme@7.2.0
          ##        with:
          ##          rdme: openapi ./ref/stardustCore.json --key=7jxMDILq5wZxTRaa4uhafttXDC8tcCOd --version=0.0.0
